<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_Anf50GtpEe-q4saeeA9lJA" name="Drug Prescription" author="SoftClansUser" bonitaVersion="7.14.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_Anf50WtpEe-q4saeeA9lJA" name="fillPrescription">
      <elements xmi:type="process:Lane" xmi:id="_Anf50mtpEe-q4saeeA9lJA" name="Technician Lane" actor="_hYJscGtpEe-q4saeeA9lJA">
        <elements xmi:type="process:StartEvent" xmi:id="_Anf502tpEe-q4saeeA9lJA" name="Start1" outgoing="_Anf56GtpEe-q4saeeA9lJA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Anf51GtpEe-q4saeeA9lJA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Anf51WtpEe-q4saeeA9lJA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Anf51mtpEe-q4saeeA9lJA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Anf512tpEe-q4saeeA9lJA" name="Enter Prescription into the system" outgoing="_Rppr4GtsEe-QQqJd8aYLNw" incoming="_Anf56GtpEe-q4saeeA9lJA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Anf52GtpEe-q4saeeA9lJA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Anf52WtpEe-q4saeeA9lJA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Anf52mtpEe-q4saeeA9lJA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Anf522tpEe-q4saeeA9lJA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Anf53GtpEe-q4saeeA9lJA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Anf53WtpEe-q4saeeA9lJA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Anf53mtpEe-q4saeeA9lJA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Anf532tpEe-q4saeeA9lJA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Anf54GtpEe-q4saeeA9lJA">
            <targetForm xmi:type="expression:Expression" xmi:id="_Anf54WtpEe-q4saeeA9lJA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Anf54mtpEe-q4saeeA9lJA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Anf542tpEe-q4saeeA9lJA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_Y2S4wGtsEe-QQqJd8aYLNw" name="Gateway1" outgoing="_aM5fUGtsEe-QQqJd8aYLNw _guN3QGtsEe-QQqJd8aYLNw" incoming="_Y2qsMGtsEe-QQqJd8aYLNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Y2Tf0WtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Y2Tf0GtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Y2Tf0mtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_guFUYGtsEe-QQqJd8aYLNw" name="Gateway2" outgoing="_le5_EGtsEe-QQqJd8aYLNw" incoming="_guN3QGtsEe-QQqJd8aYLNw _iH5nAGtsEe-QQqJd8aYLNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_guF7cWtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_guF7cGtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_guF7cmtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_zh5YsGtsEe-QQqJd8aYLNw" name="DUR Check" outgoing="_Y2qsMGtsEe-QQqJd8aYLNw" incoming="_Rppr4GtsEe-QQqJd8aYLNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RpTGkWtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RpTGkGtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RpTGkmtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_RpTGk2tsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_RpTGlGtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RpTGlWtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_RpTGl2tsEe-QQqJd8aYLNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_RpTGlmtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_zh5_yWtsEe-QQqJd8aYLNw">
            <targetForm xmi:type="expression:Expression" xmi:id="_zh5_ymtsEe-QQqJd8aYLNw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_zh5_yGtsEe-QQqJd8aYLNw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_zh7N4GtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_1IRgoGtsEe-QQqJd8aYLNw" name="Determine the insuarance coverage." outgoing="_2jvZEGtsEe-QQqJd8aYLNw" incoming="_le5_EGtsEe-QQqJd8aYLNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lexcMWtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lexcMGtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lexcMmtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lexcM2tsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lexcNGtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lexcNWtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lexcN2tsEe-QQqJd8aYLNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lexcNmtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_1IRgqmtsEe-QQqJd8aYLNw">
            <targetForm xmi:type="expression:Expression" xmi:id="_1IRgq2tsEe-QQqJd8aYLNw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_1IRgqWtsEe-QQqJd8aYLNw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_1IRgrGtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_2jorYGtsEe-QQqJd8aYLNw" name="Gateway3" outgoing="_35ZkcGtsEe-QQqJd8aYLNw __vUX0GtsEe-QQqJd8aYLNw" incoming="_2jvZEGtsEe-QQqJd8aYLNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2jorYmtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2jorYWtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2jorY2tsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="__vO4QGtsEe-QQqJd8aYLNw" name="Gateway4" outgoing="_VMww0GttEe-QQqJd8aYLNw" incoming="__vUX0GtsEe-QQqJd8aYLNw _A_xTEGttEe-QQqJd8aYLNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__vO4QmtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__vO4QWtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__vO4Q2tsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_uFPtUGttEe-QQqJd8aYLNw" name="End1" incoming="_uFdIsGttEe-QQqJd8aYLNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_uFQUYWttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_uFQUYGttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_uFQUYmttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_vFbX8GttEe-QQqJd8aYLNw" name="Pick and pack  the prescription" outgoing="_dc2XsGttEe-QQqJd8aYLNw" incoming="_VMww0GttEe-QQqJd8aYLNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VMqqMWttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VMqqMGttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VMqqMmttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VMqqM2ttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VMqqNGttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VMqqNWttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VMqqN2ttEe-QQqJd8aYLNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VMqqNmttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_vFbX-mttEe-QQqJd8aYLNw">
            <targetForm xmi:type="expression:Expression" xmi:id="_vFbX-2ttEe-QQqJd8aYLNw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_vFbX-WttEe-QQqJd8aYLNw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_vFbX_GttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_vxRxUGttEe-QQqJd8aYLNw" name="Handle pickup and payment" outgoing="_uFdIsGttEe-QQqJd8aYLNw" incoming="_mtrp4GttEe-QQqJd8aYLNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mtmxYWttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mtmxYGttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mtmxYmttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_mtmxY2ttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_mtmxZGttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_mtmxZWttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_mtmxZ2ttEe-QQqJd8aYLNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_mtmxZmttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_vxSYaWttEe-QQqJd8aYLNw">
            <targetForm xmi:type="expression:Expression" xmi:id="_vxSYamttEe-QQqJd8aYLNw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_vxSYaGttEe-QQqJd8aYLNw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_vxSYa2ttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_PdzmwGtpEe-q4saeeA9lJA" name="Pharmacist Lane" actor="_j4zrUGtpEe-q4saeeA9lJA">
        <elements xmi:type="process:Task" xmi:id="_0UaawGtsEe-QQqJd8aYLNw" name="Resolve DUR errors" outgoing="_iH5nAGtsEe-QQqJd8aYLNw" incoming="_aM5fUGtsEe-QQqJd8aYLNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aM0m0mtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aM0m0WtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aM0m02tsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_aM0m1GtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_aM0m1WtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_aM1N4GtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_aM1N4mtsEe-QQqJd8aYLNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_aM1N4WtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_0UbB2WtsEe-QQqJd8aYLNw">
            <targetForm xmi:type="expression:Expression" xmi:id="_0UbB2mtsEe-QQqJd8aYLNw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_0UbB2GtsEe-QQqJd8aYLNw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_0UbB22tsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_BzOJQGttEe-QQqJd8aYLNw" name="Determine Substitute Drug" outgoing="_A_xTEGttEe-QQqJd8aYLNw" incoming="_35ZkcGtsEe-QQqJd8aYLNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_35Td0WtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_35Td0GtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_35Td0mtsEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_35Td02tsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_35Td1GtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_35Td1WtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_35Td12tsEe-QQqJd8aYLNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_35Td1mtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_BzOwWWttEe-QQqJd8aYLNw">
            <targetForm xmi:type="expression:Expression" xmi:id="_BzOwWmttEe-QQqJd8aYLNw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_BzOwWGttEe-QQqJd8aYLNw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_BzOwW2ttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_wi1xIGttEe-QQqJd8aYLNw" name="Double check prescription" outgoing="_mtrp4GttEe-QQqJd8aYLNw" incoming="_dc2XsGttEe-QQqJd8aYLNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dcytUmttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dcytUWttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dcytU2ttEe-QQqJd8aYLNw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dcytVGttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dcytVWttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dcytVmttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dcytWGttEe-QQqJd8aYLNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dcytV2ttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_wi1xKmttEe-QQqJd8aYLNw">
            <targetForm xmi:type="expression:Expression" xmi:id="_wi1xK2ttEe-QQqJd8aYLNw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_wi1xKWttEe-QQqJd8aYLNw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_wi2YMGttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Anf55GtpEe-q4saeeA9lJA">
        <targetForm xmi:type="expression:Expression" xmi:id="_Anf55WtpEe-q4saeeA9lJA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Anf55mtpEe-q4saeeA9lJA">
        <targetForm xmi:type="expression:Expression" xmi:id="_Anf552tpEe-q4saeeA9lJA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Anf56GtpEe-q4saeeA9lJA" target="_Anf512tpEe-q4saeeA9lJA" source="_Anf502tpEe-q4saeeA9lJA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Anf56WtpEe-q4saeeA9lJA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Anf56mtpEe-q4saeeA9lJA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Rppr4GtsEe-QQqJd8aYLNw" target="_zh5YsGtsEe-QQqJd8aYLNw" source="_Anf512tpEe-q4saeeA9lJA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Rppr4WtsEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Rppr4mtsEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Y2qsMGtsEe-QQqJd8aYLNw" target="_Y2S4wGtsEe-QQqJd8aYLNw" source="_zh5YsGtsEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Y2qsMWtsEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Y2rTQGtsEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aM5fUGtsEe-QQqJd8aYLNw" target="_0UaawGtsEe-QQqJd8aYLNw" source="_Y2S4wGtsEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aM5fUWtsEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_aM5fUmtsEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_guN3QGtsEe-QQqJd8aYLNw" target="_guFUYGtsEe-QQqJd8aYLNw" source="_Y2S4wGtsEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_guN3QWtsEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_guN3QmtsEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iH5nAGtsEe-QQqJd8aYLNw" target="_guFUYGtsEe-QQqJd8aYLNw" source="_0UaawGtsEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iH5nAWtsEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_iH5nAmtsEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_le5_EGtsEe-QQqJd8aYLNw" target="_1IRgoGtsEe-QQqJd8aYLNw" source="_guFUYGtsEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_le5_EWtsEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_le5_EmtsEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2jvZEGtsEe-QQqJd8aYLNw" target="_2jorYGtsEe-QQqJd8aYLNw" source="_1IRgoGtsEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2jvZEWtsEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_2jvZEmtsEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_35ZkcGtsEe-QQqJd8aYLNw" target="_BzOJQGttEe-QQqJd8aYLNw" source="_2jorYGtsEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_35ZkcWtsEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_35ZkcmtsEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__vUX0GtsEe-QQqJd8aYLNw" target="__vO4QGtsEe-QQqJd8aYLNw" source="_2jorYGtsEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__vU-4GtsEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="__vU-4WtsEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_A_xTEGttEe-QQqJd8aYLNw" target="__vO4QGtsEe-QQqJd8aYLNw" source="_BzOJQGttEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_A_xTEWttEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_A_xTEmttEe-QQqJd8aYLNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VMww0GttEe-QQqJd8aYLNw" target="_vFbX8GttEe-QQqJd8aYLNw" source="__vO4QGtsEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VMxX4GttEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_VMxX4WttEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dc2XsGttEe-QQqJd8aYLNw" target="_wi1xIGttEe-QQqJd8aYLNw" source="_vFbX8GttEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dc2XsWttEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dc2XsmttEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mtrp4GttEe-QQqJd8aYLNw" target="_vxRxUGttEe-QQqJd8aYLNw" source="_wi1xIGttEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mtrp4WttEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_mtrp4mttEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uFdIsGttEe-QQqJd8aYLNw" target="_uFPtUGttEe-QQqJd8aYLNw" source="_vxRxUGttEe-QQqJd8aYLNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uFdIsWttEe-QQqJd8aYLNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_uFdIsmttEe-QQqJd8aYLNw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_Anf562tpEe-q4saeeA9lJA" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor"/>
      <actors xmi:type="process:Actor" xmi:id="_hYJscGtpEe-q4saeeA9lJA" name="Technician" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_j4zrUGtpEe-q4saeeA9lJA" name="Pharmacist"/>
      <contract xmi:type="process:Contract" xmi:id="_Anf57GtpEe-q4saeeA9lJA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Anf57WtpEe-q4saeeA9lJA">
        <name xmi:type="expression:Expression" xmi:id="_Anf57mtpEe-q4saeeA9lJA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Anf572tpEe-q4saeeA9lJA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Anf58GtpEe-q4saeeA9lJA">
        <name xmi:type="expression:Expression" xmi:id="_Anf58WtpEe-q4saeeA9lJA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Anf58mtpEe-q4saeeA9lJA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Anf582tpEe-q4saeeA9lJA">
        <name xmi:type="expression:Expression" xmi:id="_Anf59GtpEe-q4saeeA9lJA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Anf59WtpEe-q4saeeA9lJA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Anf59mtpEe-q4saeeA9lJA">
        <name xmi:type="expression:Expression" xmi:id="_Anf592tpEe-q4saeeA9lJA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Anf5-GtpEe-q4saeeA9lJA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Anf5-WtpEe-q4saeeA9lJA">
        <name xmi:type="expression:Expression" xmi:id="_Angg4GtpEe-q4saeeA9lJA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Angg4WtpEe-q4saeeA9lJA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_Angg4mtpEe-q4saeeA9lJA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_Angg42tpEe-q4saeeA9lJA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_Angg5GtpEe-q4saeeA9lJA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_Angg5WtpEe-q4saeeA9lJA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Angg5mtpEe-q4saeeA9lJA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Angg52tpEe-q4saeeA9lJA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Angg6GtpEe-q4saeeA9lJA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Angg6WtpEe-q4saeeA9lJA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_Angg6mtpEe-q4saeeA9lJA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Angg62tpEe-q4saeeA9lJA" type="Process" element="_Anf50GtpEe-q4saeeA9lJA" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_Angg7GtpEe-q4saeeA9lJA" type="2007" element="_Anf50WtpEe-q4saeeA9lJA">
      <children xmi:type="notation:DecorationNode" xmi:id="_Angg7WtpEe-q4saeeA9lJA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Angg7mtpEe-q4saeeA9lJA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_Angg72tpEe-q4saeeA9lJA" type="3007" element="_Anf50mtpEe-q4saeeA9lJA">
          <children xmi:type="notation:DecorationNode" xmi:id="_Angg8GtpEe-q4saeeA9lJA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Angg8WtpEe-q4saeeA9lJA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Angg8mtpEe-q4saeeA9lJA" type="3005" element="_Anf512tpEe-q4saeeA9lJA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Angg82tpEe-q4saeeA9lJA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Angg9GtpEe-q4saeeA9lJA" x="182" y="97" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Angg9WtpEe-q4saeeA9lJA" type="3002" element="_Anf502tpEe-q4saeeA9lJA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Angg9mtpEe-q4saeeA9lJA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Angg92tpEe-q4saeeA9lJA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Angg-GtpEe-q4saeeA9lJA" x="60" y="120"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Y2Ut8GtsEe-QQqJd8aYLNw" type="3009" element="_Y2S4wGtsEe-QQqJd8aYLNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Y2VVAGtsEe-QQqJd8aYLNw" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Y2VVAWtsEe-QQqJd8aYLNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Y2Ut8WtsEe-QQqJd8aYLNw" x="638" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_guHJkGtsEe-QQqJd8aYLNw" type="3009" element="_guFUYGtsEe-QQqJd8aYLNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_guHwoGtsEe-QQqJd8aYLNw" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_guHwoWtsEe-QQqJd8aYLNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_guHJkWtsEe-QQqJd8aYLNw" x="782" y="115"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zh7N4WtsEe-QQqJd8aYLNw" type="3005" element="_zh5YsGtsEe-QQqJd8aYLNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zh708GtsEe-QQqJd8aYLNw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zh7N4mtsEe-QQqJd8aYLNw" x="416" y="100" width="141" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1IRgrWtsEe-QQqJd8aYLNw" type="3005" element="_1IRgoGtsEe-QQqJd8aYLNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1IRgr2tsEe-QQqJd8aYLNw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1IRgrmtsEe-QQqJd8aYLNw" x="902" y="90" width="167" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2jp5gGtsEe-QQqJd8aYLNw" type="3009" element="_2jorYGtsEe-QQqJd8aYLNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_2jp5gmtsEe-QQqJd8aYLNw" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_2jp5g2tsEe-QQqJd8aYLNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2jp5gWtsEe-QQqJd8aYLNw" x="1144" y="109"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__vPfUGtsEe-QQqJd8aYLNw" type="3009" element="__vO4QGtsEe-QQqJd8aYLNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="__vQGYGtsEe-QQqJd8aYLNw" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="__vQGYWtsEe-QQqJd8aYLNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__vPfUWtsEe-QQqJd8aYLNw" x="1275" y="108"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uFRigGttEe-QQqJd8aYLNw" type="3003" element="_uFPtUGttEe-QQqJd8aYLNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_uFRigmttEe-QQqJd8aYLNw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_uFRig2ttEe-QQqJd8aYLNw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uFRigWttEe-QQqJd8aYLNw" x="1902" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vFb_AGttEe-QQqJd8aYLNw" type="3005" element="_vFbX8GttEe-QQqJd8aYLNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vFb_AmttEe-QQqJd8aYLNw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vFb_AWttEe-QQqJd8aYLNw" x="1403" y="88" width="168" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vxSYbGttEe-QQqJd8aYLNw" type="3005" element="_vxRxUGttEe-QQqJd8aYLNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vxS_cGttEe-QQqJd8aYLNw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vxSYbWttEe-QQqJd8aYLNw" x="1694" y="87" width="152" height="76"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Angg-WtpEe-q4saeeA9lJA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Angg-mtpEe-q4saeeA9lJA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Angg-2tpEe-q4saeeA9lJA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Angg_GtpEe-q4saeeA9lJA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Angg_WtpEe-q4saeeA9lJA"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_Pd8wsGtpEe-q4saeeA9lJA" type="3007" element="_PdzmwGtpEe-q4saeeA9lJA">
          <children xmi:type="notation:DecorationNode" xmi:id="_Pd9XwGtpEe-q4saeeA9lJA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Pd9XwWtpEe-q4saeeA9lJA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_0Ubo4GtsEe-QQqJd8aYLNw" type="3005" element="_0UaawGtsEe-QQqJd8aYLNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0UcP8GtsEe-QQqJd8aYLNw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Ubo4WtsEe-QQqJd8aYLNw" x="590" y="103" width="166" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BzOwXGttEe-QQqJd8aYLNw" type="3005" element="_BzOJQGttEe-QQqJd8aYLNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BzPXYGttEe-QQqJd8aYLNw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BzOwXWttEe-QQqJd8aYLNw" x="1078" y="96" width="176" height="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wi2YMWttEe-QQqJd8aYLNw" type="3005" element="_wi1xIGttEe-QQqJd8aYLNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wi2YM2ttEe-QQqJd8aYLNw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wi2YMmttEe-QQqJd8aYLNw" x="1406" y="105" width="160" height="80"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Pd8wsWtpEe-q4saeeA9lJA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Pd8wsmtpEe-q4saeeA9lJA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Pd8ws2tpEe-q4saeeA9lJA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Pd9XwmtpEe-q4saeeA9lJA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pd8wtGtpEe-q4saeeA9lJA" x="28" y="250" width="1292" height="279"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Angg_mtpEe-q4saeeA9lJA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Angg_2tpEe-q4saeeA9lJA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AnghAGtpEe-q4saeeA9lJA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_AnghAWtpEe-q4saeeA9lJA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AnghAmtpEe-q4saeeA9lJA" width="2065" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_AnghA2tpEe-q4saeeA9lJA"/>
    <edges xmi:type="notation:Connector" xmi:id="_AnghBGtpEe-q4saeeA9lJA" type="4001" element="_Anf56GtpEe-q4saeeA9lJA" source="_Angg9WtpEe-q4saeeA9lJA" target="_Angg8mtpEe-q4saeeA9lJA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AnghBWtpEe-q4saeeA9lJA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AnghBmtpEe-q4saeeA9lJA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AnghB2tpEe-q4saeeA9lJA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AnghCGtpEe-q4saeeA9lJA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Rpq6AGtsEe-QQqJd8aYLNw" type="4001" element="_Rppr4GtsEe-QQqJd8aYLNw" source="_Angg8mtpEe-q4saeeA9lJA" target="_zh7N4WtsEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RprhEGtsEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RprhEWtsEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Rpq6AWtsEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Rpq6AmtsEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Y2r6UGtsEe-QQqJd8aYLNw" type="4001" element="_Y2qsMGtsEe-QQqJd8aYLNw" source="_zh7N4WtsEe-QQqJd8aYLNw" target="_Y2Ut8GtsEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Y2shYmtsEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Y2shY2tsEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Y2shYGtsEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Y2shYWtsEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aM6GYGtsEe-QQqJd8aYLNw" type="4001" element="_aM5fUGtsEe-QQqJd8aYLNw" source="_Y2Ut8GtsEe-QQqJd8aYLNw" target="_0Ubo4GtsEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aM6GY2tsEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aM6GZGtsEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aM6GYWtsEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aM6GYmtsEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_guOeUGtsEe-QQqJd8aYLNw" type="4001" element="_guN3QGtsEe-QQqJd8aYLNw" source="_Y2Ut8GtsEe-QQqJd8aYLNw" target="_guHJkGtsEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_guPFYGtsEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_guPFYWtsEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_guOeUWtsEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_guOeUmtsEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iH61IGtsEe-QQqJd8aYLNw" type="4001" element="_iH5nAGtsEe-QQqJd8aYLNw" source="_0Ubo4GtsEe-QQqJd8aYLNw" target="_guHJkGtsEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iH7cMGtsEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iH7cMWtsEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iH61IWtsEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iH61ImtsEe-QQqJd8aYLNw" points="[0, 0, -64, 225]$[63, -225, -1, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iH_toGtsEe-QQqJd8aYLNw" id="(1.0,0.30120481927710846)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iH_toWtsEe-QQqJd8aYLNw" id="(0.3953488372093023,0.8837209302325582)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_le7NMGtsEe-QQqJd8aYLNw" type="4001" element="_le5_EGtsEe-QQqJd8aYLNw" source="_guHJkGtsEe-QQqJd8aYLNw" target="_1IRgrWtsEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_le7NM2tsEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_le7NNGtsEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_le7NMWtsEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_le7NMmtsEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2jvZE2tsEe-QQqJd8aYLNw" type="4001" element="_2jvZEGtsEe-QQqJd8aYLNw" source="_1IRgrWtsEe-QQqJd8aYLNw" target="_2jp5gGtsEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2jwnMGtsEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2jwnMWtsEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2jvZFGtsEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2jvZFWtsEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_35aLgGtsEe-QQqJd8aYLNw" type="4001" element="_35ZkcGtsEe-QQqJd8aYLNw" source="_2jp5gGtsEe-QQqJd8aYLNw" target="_BzOwXGttEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_35aLg2tsEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_35aLhGtsEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_35aLgWtsEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_35aLgmtsEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__vVl8GtsEe-QQqJd8aYLNw" type="4001" element="__vUX0GtsEe-QQqJd8aYLNw" source="_2jp5gGtsEe-QQqJd8aYLNw" target="__vPfUGtsEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__vVl82tsEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__vVl9GtsEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__vVl8WtsEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__vVl8mtsEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_A_x6IGttEe-QQqJd8aYLNw" type="4001" element="_A_xTEGttEe-QQqJd8aYLNw" source="_BzOwXGttEe-QQqJd8aYLNw" target="__vPfUGtsEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_A_yhMGttEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_A_yhMWttEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_A_x6IWttEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_A_x6ImttEe-QQqJd8aYLNw" points="[0, 0, -42, 224]$[41, -224, -1, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_A_zvUGttEe-QQqJd8aYLNw" id="(1.0,0.3181818181818182)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_A_zvUWttEe-QQqJd8aYLNw" id="(0.4883720930232558,0.9767441860465116)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VMxX4mttEe-QQqJd8aYLNw" type="4001" element="_VMww0GttEe-QQqJd8aYLNw" source="__vPfUGtsEe-QQqJd8aYLNw" target="_vFb_AGttEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VMxX5WttEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VMxX5mttEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VMxX42ttEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VMxX5GttEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dc2-wGttEe-QQqJd8aYLNw" type="4001" element="_dc2XsGttEe-QQqJd8aYLNw" source="_vFb_AGttEe-QQqJd8aYLNw" target="_wi2YMWttEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dc2-w2ttEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dc2-xGttEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dc2-wWttEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dc2-wmttEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mtsQ8GttEe-QQqJd8aYLNw" type="4001" element="_mtrp4GttEe-QQqJd8aYLNw" source="_wi2YMWttEe-QQqJd8aYLNw" target="_vxSYbGttEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mtsQ82ttEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mtsQ9GttEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mtsQ8WttEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mtsQ8mttEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uFdvwGttEe-QQqJd8aYLNw" type="4001" element="_uFdIsGttEe-QQqJd8aYLNw" source="_vxSYbGttEe-QQqJd8aYLNw" target="_uFRigGttEe-QQqJd8aYLNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uFdvw2ttEe-QQqJd8aYLNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uFdvxGttEe-QQqJd8aYLNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uFdvwWttEe-QQqJd8aYLNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uFdvwmttEe-QQqJd8aYLNw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
